# Generated by Django 4.2.3 on 2023-07-31 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-modify_dt",),
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
        migrations.RenameField(
            model_name="post",
            old_name="create_date",
            new_name="create_dt",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="modify_date",
            new_name="modify_dt",
        ),
    ]
